### ISSUE TITLE
use travis-ci cache

### ISSUE THREAD

**Issue by goto-bus-stop** [u-wave/web#437]
Something like

```yaml
cache:
  directories:
    - "node_modules"
```

Should speed our CI runs up a bunch
